spring:
  datasource:
    url: jdbc:h2:/Users/dkurnikov/IdeaProjects/demo/demoDataSource
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoint:
    health:
      show-details: always
